### ISSUE TITLE
config.error 

### ISSUE THREAD

**Issue by Portulaca666** [StanfordASL/MATS#1]
`python2.7 /root/software/RNASeq-MATS.py -b1 cat b11.txt-b2cat b22.txt -gtf /root/software/gtf/hg38.knownGene.gtf -o out_test -t single -len 100 -a 8 -r1 72,75 -sd1 40,35 -r2 70,65 -sd2 48,45 8 -c 0.05 -analysis P -expressionChange 20`
I used this code and I have no idea that why the output file need a config.txt ?
The software is MATS.3.0.5.beta.
![image](https://user-images.githubusercontent.com/70992194/160639977-30da00cd-3f84-4ef7-b405-c43cf17a9fbf.png)

**Comment by BorisIvanovic** [comment]
Hi @wuzhigui,

I think you may have instead been looking for the page for [this toolkit](http://rnaseq-mats.sourceforge.net/)? On it, I can see that the authors ask for any comments or questions to be posted on the [rMATS Users Google Group](https://groups.google.com/forum/#!forum/rmats-user-group).

Hope this helps!
